### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by HDavo**

### CODE REVIEW

**Comment by andyholmes** [comment]
Thanks! Can you squash your commits into one, like `feat(i18n): add Spanish translation`?

**Comment by HDavo** [comment]
Yes, I'll do it tomorrow. Should I submit a new pull request after that?
Sorry if it is a silly question.

**Comment by andyholmes** [comment]
You can just squash into one commit and then force push :)

**Comment by HDavo** [comment]
The squash and the force push are done.

**Comment by andyholmes** [comment]
Thanks!

**Pull request merged**
