### PR TITLE
Make the AlbumArt icon a symbolic icon

### PR DESCRIPTION
**Pull request by vixalien**
| Before | After |
|---|----|
|Screenshot from 2024-03-31 15-58-53 | image |

### CODE REVIEW

**Comment by andyholmes** [comment]
Nice one, thanks!

**Comment by vixalien** [comment]
On a slightly unrelated note, wouldn't it be better to show the icon as the one shown by gnome-shell?

image

**Comment by andyholmes** [comment]
I guess if the assumption is that it will always be music. I went for a more generic icon, since it's about 50/50 for me.

**Comment by vixalien** [comment]
> I guess if the assumption is that it will always be music. I went for a more generic icon, since it's about 50/50 for me.

Ah, I'd say the beamed note more represents music/audio, while the current one would more represent streaming or radio.

**Comment by andyholmes** [comment]
Yeah, there's this one:

An old ugly 00's symbolic icon for mixed media

But that kind screams early-00's media player 😅 I guess I'd be okay using what GNOME Shell uses, unless there's a better one or we can trick a designer into making one.

**Pull request merged**
